//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/annotation/src/main/java/java/lang/annotation/Annotation.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"

@protocol JavaLangAnnotationAnnotation < NSObject >
- (IOSClass *)annotationType;
- (BOOL)isEqual:(id)obj;
- (NSUInteger)hash;
- (NSString *)description;
@end
