//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/jos/samples/controls/controls/EventListener.java
//
//  Created by rwl on 2/13/13.
//

void JosSamplesControlsControlsEventListener_unused() {}
