//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/BufferUnderflowException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaNioBufferUnderflowException_serialVersionUID -1713313658691622206

@interface JavaNioBufferUnderflowException : JavaLangRuntimeException {
}

- (id)init;
@end
