//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/BufferOverflowException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaNioBufferOverflowException_serialVersionUID -5484897634319144535

@interface JavaNioBufferOverflowException : JavaLangRuntimeException {
}

- (id)init;
@end
