//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/DoubleArrayBuffer.java
//
//  Created by rwl on 2/1/13.
//

@class IOSDoubleArray;
@class JavaNioByteOrder;

#import "JreEmulation.h"
#import "java/nio/DoubleBuffer.h"

@interface JavaNioDoubleArrayBuffer : JavaNioDoubleBuffer {
 @public
  IOSDoubleArray *backingArray_;
  int offset_;
}

@property (nonatomic, retain) IOSDoubleArray *backingArray;
@property (nonatomic, assign) int offset;

- (id)initWithJavaLangDoubleArray:(IOSDoubleArray *)array;
- (id)initWithInt:(int)capacity;
- (id)initWithInt:(int)capacity
withJavaLangDoubleArray:(IOSDoubleArray *)backingArray
          withInt:(int)offset;
- (double)get;
- (double)getWithInt:(int)index;
- (JavaNioDoubleBuffer *)getWithJavaLangDoubleArray:(IOSDoubleArray *)dest
                                            withInt:(int)off
                                            withInt:(int)len;
- (BOOL)isDirect;
- (JavaNioByteOrder *)order;
@end
