//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/InvalidMarkException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/IllegalStateException.h"

#define JavaNioInvalidMarkException_serialVersionUID 1698329710438510774

@interface JavaNioInvalidMarkException : JavaLangIllegalStateException {
}

- (id)init;
@end
