//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/ShortArrayBuffer.java
//
//  Created by rwl on 2/1/13.
//

@class IOSShortArray;
@class JavaNioByteOrder;

#import "JreEmulation.h"
#import "java/nio/ShortBuffer.h"

@interface JavaNioShortArrayBuffer : JavaNioShortBuffer {
 @public
  IOSShortArray *backingArray_;
  int offset_;
}

@property (nonatomic, retain) IOSShortArray *backingArray;
@property (nonatomic, assign) int offset;

- (id)initWithJavaLangShortArray:(IOSShortArray *)array;
- (id)initWithInt:(int)capacity;
- (id)initWithInt:(int)capacity
withJavaLangShortArray:(IOSShortArray *)backingArray
          withInt:(int)offset;
- (short int)get;
- (short int)getWithInt:(int)index;
- (JavaNioShortBuffer *)getWithJavaLangShortArray:(IOSShortArray *)dest
                                          withInt:(int)off
                                          withInt:(int)len;
- (BOOL)isDirect;
- (JavaNioByteOrder *)order;
@end
