//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/Error.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/Throwable.h"

#define JavaLangError_serialVersionUID 4980196508277280342

@interface JavaLangError : JavaLangThrowable {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
- (id)initWithNSString:(NSString *)detailMessage
 withJavaLangThrowable:(JavaLangThrowable *)throwable;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)throwable;
@end
