//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/ExceptionInInitializerError.java
//
//  Created by rwl on 2/1/13.
//

@class JavaLangThrowable;

#import "JreEmulation.h"
#import "java/lang/LinkageError.h"

#define JavaLangExceptionInInitializerError_serialVersionUID 1521711792217232256

@interface JavaLangExceptionInInitializerError : JavaLangLinkageError {
 @public
  JavaLangThrowable *exception_;
}

@property (nonatomic, retain) JavaLangThrowable *exception;

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)exception;
- (JavaLangThrowable *)getException;
- (JavaLangThrowable *)getCause;
@end
