//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/IllegalThreadStateException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/IllegalArgumentException.h"

#define JavaLangIllegalThreadStateException_serialVersionUID -7626246362397460174

@interface JavaLangIllegalThreadStateException : JavaLangIllegalArgumentException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
