//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/InternalError.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/Error.h"

#define JavaLangInternalError_serialVersionUID -9062593416125562365

@interface JavaLangInternalError : JavaLangError {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
