//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/Iterable.java
//
//  Created by rwl on 2/1/13.
//

@protocol JavaUtilIterator;

#import "JreEmulation.h"

@protocol JavaLangIterable < NSObject >
- (id<JavaUtilIterator>)iterator;
@end
