//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/LinkageError.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/Error.h"

#define JavaLangLinkageError_serialVersionUID 3579600108157160122

@interface JavaLangLinkageError : JavaLangError {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
