//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/NumberFormatException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/IllegalArgumentException.h"

#define JavaLangNumberFormatException_serialVersionUID -2848938806368998894

@interface JavaLangNumberFormatException : JavaLangIllegalArgumentException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
