//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/SecurityException.java
//
//  Created by rwl on 2/1/13.
//

@class JavaLangThrowable;

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaLangSecurityException_serialVersionUID 6878364983674394167

@interface JavaLangSecurityException : JavaLangRuntimeException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
- (id)initWithNSString:(NSString *)message
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)cause;
@end
