//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/StringIndexOutOfBoundsException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/IndexOutOfBoundsException.h"

#define JavaLangStringIndexOutOfBoundsException_serialVersionUID -6762910422159637258

@interface JavaLangStringIndexOutOfBoundsException : JavaLangIndexOutOfBoundsException {
}

- (id)init;
- (id)initWithInt:(int)index;
- (id)initWithNSString:(NSString *)detailMessage;
@end
