//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/lang/System.java
//
//  Created by rwl on 2/1/13.
//

@class JavaIoPrintStream;
@class JavaUtilProperties;

#import "JreEmulation.h"
#import "java/io/OutputStream.h"

@interface JavaLangSystem : NSObject {
}

+ (JavaUtilProperties *)props;
+ (void)setPropsWithJavaUtilProperties:(JavaUtilProperties *)props;
+ (JavaIoPrintStream *)out;
+ (JavaIoPrintStream *)err;
+ (long long int)currentTimeMillis;
+ (int)identityHashCodeWithId:(id)anObject;
+ (void)arraycopyWithId:(id)src
                withInt:(int)srcPos
                 withId:(id)dest
                withInt:(int)destPos
                withInt:(int)length;
+ (long long int)nanoTime;
+ (void)exitWithInt:(int)status;
+ (JavaUtilProperties *)getProperties;
+ (void)setSystemPropertiesWithJavaUtilProperties:(JavaUtilProperties *)props;
+ (NSString *)getPropertyWithNSString:(NSString *)key;
+ (NSString *)getPropertyWithNSString:(NSString *)key
                         withNSString:(NSString *)defaultValue;
+ (void)setPropertyWithNSString:(NSString *)key
                   withNSString:(NSString *)value;
+ (void)setPropertiesWithJavaUtilProperties:(JavaUtilProperties *)properties;
+ (NSString *)clearPropertyWithNSString:(NSString *)key;
@end

@interface JavaLangSystem_$1 : JavaIoOutputStream {
}

- (void)writeWithInt:(int)b;
@end

@interface JavaLangSystem_$2 : JavaIoOutputStream {
}

- (void)writeWithInt:(int)b;
@end
