//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/ThreadDeath.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/Error.h"

#define JavaLangThreadDeath_serialVersionUID -4417128565033088268

@interface JavaLangThreadDeath : JavaLangError {
}

- (id)init;
@end
