//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/concurrent/ConcurrentHashMap.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/util/Hashtable.h"
#import "java/util/concurrent/ConcurrentMap.h"

@interface JavaUtilConcurrentConcurrentHashMap : JavaUtilHashtable < JavaUtilConcurrentConcurrentMap > {
}

- (id)putIfAbsentWithId:(id)key
                 withId:(id)value;
- (BOOL)removeWithId:(id)key
              withId:(id)value;
- (BOOL)replaceWithId:(id)key
               withId:(id)oldValue
               withId:(id)newValue;
- (id)replaceWithId:(id)key
             withId:(id)value;
@end
