//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/concurrent/Executor.java
//
//  Created by rwl on 2/1/13.
//

@protocol JavaLangRunnable;

#import "JreEmulation.h"

@protocol JavaUtilConcurrentExecutor < NSObject >
- (void)executeWithJavaLangRunnable:(id<JavaLangRunnable>)command;
@end
