//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/concurrent/Future.java
//
//  Created by rwl on 2/1/13.
//

@class JavaUtilConcurrentTimeUnitEnum;

#import "JreEmulation.h"

@protocol JavaUtilConcurrentFuture < NSObject >
- (BOOL)cancelWithBOOL:(BOOL)mayInterruptIfRunning;
- (BOOL)isCancelled;
- (BOOL)isDone;
- (id)get;
- (id)getWithLongInt:(long long int)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;
@end
