//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/logging/Handler.java
//
//  Created by rwl on 2/1/13.
//

@class JavaUtilLoggingFormatter;
@class JavaUtilLoggingLevel;
@class JavaUtilLoggingLogRecord;

#import "JreEmulation.h"

@interface JavaUtilLoggingHandler : NSObject {
 @public
  JavaUtilLoggingFormatter *formatter_;
  JavaUtilLoggingLevel *level_;
}

@property (nonatomic, retain) JavaUtilLoggingFormatter *formatter;
@property (nonatomic, retain) JavaUtilLoggingLevel *level;

- (void)close;
- (void)flush;
- (JavaUtilLoggingFormatter *)getFormatter;
- (JavaUtilLoggingLevel *)getLevel;
- (BOOL)isLoggableWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
- (void)publishWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
- (void)setFormatterWithJavaUtilLoggingFormatter:(JavaUtilLoggingFormatter *)newFormatter;
- (void)setLevelWithJavaUtilLoggingLevel:(JavaUtilLoggingLevel *)newLevel;
@end
