//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/logging/LogManager.java
//
//  Created by rwl on 2/1/13.
//

@class JavaUtilHashMap;

#import "JreEmulation.h"
#import "java/util/logging/Logger.h"

@interface JavaUtilLoggingLogManager : NSObject {
 @public
  JavaUtilHashMap *loggerList_;
  JavaUtilLoggingLogger *rootLogger_;
}

@property (nonatomic, retain) JavaUtilHashMap *loggerList;
@property (nonatomic, retain) JavaUtilLoggingLogger *rootLogger;

+ (JavaUtilLoggingLogManager *)singleton;
+ (void)setSingletonWithJavaUtilLoggingLogManager:(JavaUtilLoggingLogManager *)singleton;
+ (JavaUtilLoggingLogManager *)getLogManager;
- (id)init;
- (BOOL)addLoggerWithJavaUtilLoggingLogger:(JavaUtilLoggingLogger *)logger;
- (JavaUtilLoggingLogger *)getLoggerWithNSString:(NSString *)name;
- (void)addLoggerWithoutDuplicationCheckingWithJavaUtilLoggingLogger:(JavaUtilLoggingLogger *)logger;
- (JavaUtilLoggingLogger *)getOrAddLoggerWithNSString:(NSString *)name;
@end

@interface JavaUtilLoggingLogManager_RootLogger : JavaUtilLoggingLogger {
 @public
  JavaUtilLoggingLogManager *this$0_;
}

@property (nonatomic, retain) JavaUtilLoggingLogManager *this$0;

- (id)initWithJavaUtilLoggingLogManager:(JavaUtilLoggingLogManager *)outer$0;
@end
