//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/logging/NSLogHandler.java
//
//  Created by rwl on 2/1/13.
//

@class JavaUtilLoggingLogRecord;

#import "JreEmulation.h"
#import "java/util/logging/Formatter.h"
#import "java/util/logging/Handler.h"

@interface JavaUtilLoggingNSLogHandler : JavaUtilLoggingHandler {
}

- (id)init;
- (void)close;
- (void)flush;
- (void)publishWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
- (void)logWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
@end

@interface JavaUtilLoggingNSLogHandler_NSLogFormatter : JavaUtilLoggingFormatter {
 @public
  JavaUtilLoggingNSLogHandler *this$0_;
}

@property (nonatomic, retain) JavaUtilLoggingNSLogHandler *this$0;

- (NSString *)formatWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
- (id)initWithJavaUtilLoggingNSLogHandler:(JavaUtilLoggingNSLogHandler *)outer$0;
@end
