//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/junit/build_result/java/junit/framework/AssertionFailedError.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/AssertionError.h"

#define JunitFrameworkAssertionFailedError_serialVersionUID 1

@interface JunitFrameworkAssertionFailedError : JavaLangAssertionError {
}

- (id)init;
- (id)initWithNSString:(NSString *)message;
+ (NSString *)defaultStringWithNSString:(NSString *)message;
@end
