//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/junit/build_result/java/junit/framework/Protectable.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"

@protocol JunitFrameworkProtectable < NSObject >
- (void)protect;
@end
