//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/junit/build_result/java/junit/framework/Test.java
//
//  Created by rwl on 2/1/13.
//

@class JunitFrameworkTestResult;

#import "JreEmulation.h"

@protocol JunitFrameworkTest < NSObject >
- (int)countTestCases;
- (void)runWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;
@end
