//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/android/libcore/luni/src/main/java/java/util/regex/MatchResult.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"

@protocol JavaUtilRegexMatchResult < NSObject >
- (int)end;
- (int)endWithInt:(int)group;
- (NSString *)group;
- (NSString *)groupWithInt:(int)group;
- (int)groupCount;
- (int)start;
- (int)startWithInt:(int)group;
@end
