//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/math/src/main/java/java/math/Conversion.java
//
//  Created by rwl on 2/1/13.
//

@class IOSIntArray;
@class JavaMathBigInteger;

#import "JreEmulation.h"

@interface JavaMathConversion : NSObject {
}

- (id)init;
+ (IOSIntArray *)digitFitInInt;
+ (IOSIntArray *)bigRadices;
+ (NSString *)bigInteger2StringWithJavaMathBigInteger:(JavaMathBigInteger *)val
                                              withInt:(int)radix;
+ (NSString *)toDecimalScaledStringWithJavaMathBigInteger:(JavaMathBigInteger *)val
                                                  withInt:(int)scale_;
+ (NSString *)toDecimalScaledStringWithLongInt:(long long int)value
                                       withInt:(int)scale_;
+ (long long int)divideLongByBillionWithLongInt:(long long int)a;
+ (double)bigInteger2DoubleWithJavaMathBigInteger:(JavaMathBigInteger *)val;
@end
