//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/BufferedWriter.java
//
//  Created by rwl on 2/1/13.
//

@class IOSCharArray;

#import "JreEmulation.h"
#import "java/io/Writer.h"

@interface JavaIoBufferedWriter : JavaIoWriter {
 @public
  JavaIoWriter *out_;
  IOSCharArray *buf_;
  int pos_;
  NSString *lineSeparator_;
}

@property (nonatomic, retain) JavaIoWriter *out;
@property (nonatomic, retain) IOSCharArray *buf;
@property (nonatomic, assign) int pos;
@property (nonatomic, copy) NSString *lineSeparator;

- (id)initWithJavaIoWriter:(JavaIoWriter *)outArg;
- (id)initWithJavaIoWriter:(JavaIoWriter *)outArg
                   withInt:(int)size;
- (void)close;
- (void)flush;
- (void)flushInternal;
- (BOOL)isClosed;
- (void)newLine OBJC_METHOD_FAMILY_NONE;
- (void)writeWithJavaLangCharacterArray:(IOSCharArray *)cbuf
                                withInt:(int)offset
                                withInt:(int)count;
- (void)writeWithInt:(int)oneChar;
- (void)writeWithNSString:(NSString *)str
                  withInt:(int)offset
                  withInt:(int)count;
@end
