//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/FileFilter.java
//
//  Created by rwl on 2/1/13.
//

@class JavaIoFile;

#import "JreEmulation.h"

@protocol JavaIoFileFilter < NSObject >
- (BOOL)acceptWithJavaIoFile:(JavaIoFile *)pathname;
@end
