//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/FilterInputStream.java
//
//  Created by rwl on 2/1/13.
//

@class IOSByteArray;

#import "JreEmulation.h"
#import "java/io/InputStream.h"

@interface JavaIoFilterInputStream : JavaIoInputStream {
 @public
  JavaIoInputStream *in_;
}

@property (nonatomic, retain) JavaIoInputStream *in;

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg;
- (int)available;
- (void)close;
- (void)markWithInt:(int)readlimit;
- (BOOL)markSupported;
- (int)read;
- (int)readWithJavaLangByteArray:(IOSByteArray *)buffer;
- (int)readWithJavaLangByteArray:(IOSByteArray *)buffer
                         withInt:(int)offset
                         withInt:(int)count;
- (void)reset;
- (long long int)skipWithLongInt:(long long int)count;
@end
