//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/InterruptedIOException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/io/IOException.h"

#define JavaIoInterruptedIOException_serialVersionUID 4020568460727500567

@interface JavaIoInterruptedIOException : JavaIoIOException {
 @public
  int bytesTransferred_;
}

@property (nonatomic, assign) int bytesTransferred;

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
