//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/InvalidObjectException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/io/ObjectStreamException.h"

#define JavaIoInvalidObjectException_serialVersionUID 3233174318281839583

@interface JavaIoInvalidObjectException : JavaIoObjectStreamException {
}

- (id)initWithNSString:(NSString *)detailMessage;
@end
