//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/IOException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/Exception.h"

@interface JavaIoIOException : JavaLangException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
