//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/ObjectStreamException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/io/IOException.h"

#define JavaIoObjectStreamException_serialVersionUID 7260898174833392607

@interface JavaIoObjectStreamException : JavaIoIOException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
