//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/UnsupportedEncodingException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/io/IOException.h"

#define JavaIoUnsupportedEncodingException_serialVersionUID -4274276298326136670

@interface JavaIoUnsupportedEncodingException : JavaIoIOException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
