//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/AbstractMap.java
//
//  Created by rwl on 2/1/13.
//

@class JavaUtilAbstractMap_$1;
@class JavaUtilAbstractMap_$2;
@protocol JavaUtilCollection;
@protocol JavaUtilSet;

#import "JreEmulation.h"
#import "java/util/AbstractCollection.h"
#import "java/util/AbstractSet.h"
#import "java/util/Iterator.h"
#import "java/util/Map.h"

@interface JavaUtilAbstractMap : NSObject < JavaUtilMap > {
 @public
  id<JavaUtilSet> keySet__;
  id<JavaUtilCollection> valuesCollection_;
}

@property (nonatomic, retain) id<JavaUtilSet> keySet_;
@property (nonatomic, retain) id<JavaUtilCollection> valuesCollection;

- (id)init;
- (void)clear;
- (BOOL)containsKeyWithId:(id)key;
- (BOOL)containsValueWithId:(id)value;
- (id<JavaUtilSet>)entrySet;
- (BOOL)isEqual:(id)object;
- (id)getWithId:(id)key;
- (NSUInteger)hash;
- (BOOL)isEmpty;
- (id<JavaUtilSet>)keySet;
- (id)putWithId:(id)key
         withId:(id)value;
- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)map;
- (id)removeWithId:(id)key;
- (int)size;
- (NSString *)description;
- (id<JavaUtilCollection>)values;
- (id)clone;
@end

@interface JavaUtilAbstractMap_$1 : JavaUtilAbstractSet {
 @public
  JavaUtilAbstractMap *this$0_;
}

@property (nonatomic, retain) JavaUtilAbstractMap *this$0;

- (BOOL)containsWithId:(id)object;
- (int)size;
- (id<JavaUtilIterator>)iterator;
- (id)initWithJavaUtilAbstractMap:(JavaUtilAbstractMap *)outer$0;
@end

@interface JavaUtilAbstractMap_$1_$1 : NSObject < JavaUtilIterator > {
 @public
  JavaUtilAbstractMap_$1 *this$0_;
  id<JavaUtilIterator> setIterator_;
}

@property (nonatomic, retain) JavaUtilAbstractMap_$1 *this$0;
@property (nonatomic, retain) id<JavaUtilIterator> setIterator;

- (BOOL)hasNext;
- (id)next;
- (void)remove;
- (id)initWithJavaUtilAbstractMap_$1:(JavaUtilAbstractMap_$1 *)outer$0;
@end

@interface JavaUtilAbstractMap_$2 : JavaUtilAbstractCollection {
 @public
  JavaUtilAbstractMap *this$0_;
}

@property (nonatomic, retain) JavaUtilAbstractMap *this$0;

- (int)size;
- (BOOL)containsWithId:(id)object;
- (id<JavaUtilIterator>)iterator;
- (id)initWithJavaUtilAbstractMap:(JavaUtilAbstractMap *)outer$0;
@end

@interface JavaUtilAbstractMap_$2_$1 : NSObject < JavaUtilIterator > {
 @public
  JavaUtilAbstractMap_$2 *this$0_;
  id<JavaUtilIterator> setIterator_;
}

@property (nonatomic, retain) JavaUtilAbstractMap_$2 *this$0;
@property (nonatomic, retain) id<JavaUtilIterator> setIterator;

- (BOOL)hasNext;
- (id)next;
- (void)remove;
- (id)initWithJavaUtilAbstractMap_$2:(JavaUtilAbstractMap_$2 *)outer$0;
@end
