//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/AbstractSet.java
//
//  Created by rwl on 2/1/13.
//

@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "java/util/AbstractCollection.h"
#import "java/util/Set.h"

@interface JavaUtilAbstractSet : JavaUtilAbstractCollection < JavaUtilSet > {
}

- (id)init;
- (BOOL)isEqual:(id)object;
- (NSUInteger)hash;
- (BOOL)removeAllWithJavaUtilCollection:(id<JavaUtilCollection>)collection;
@end
