//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/Enumeration.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"

@protocol JavaUtilEnumeration < NSObject >
- (BOOL)hasMoreElements;
- (id)nextElement;
@end
