//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/EnumSet.java
//
//  Created by rwl on 2/1/13.
//

@class IOSObjectArray;
@class JavaLangEnum;
@protocol JavaUtilCollection;

#import "JreEmulation.h"
#import "java/io/Serializable.h"
#import "java/util/AbstractSet.h"

#define JavaUtilEnumSet_serialVersionUID 1009687484059888093

@interface JavaUtilEnumSet : JavaUtilAbstractSet < NSCopying, JavaIoSerializable > {
 @public
  IOSClass *elementClass_;
}

@property (nonatomic, retain) IOSClass *elementClass;

- (id)initWithIOSClass:(IOSClass *)cls;
+ (JavaUtilEnumSet *)noneOfWithIOSClass:(IOSClass *)elementType;
+ (JavaUtilEnumSet *)allOfWithIOSClass:(IOSClass *)elementType;
+ (JavaUtilEnumSet *)copyOfWithJavaUtilEnumSet:(JavaUtilEnumSet *)s OBJC_METHOD_FAMILY_NONE;
+ (JavaUtilEnumSet *)copyOfWithJavaUtilCollection:(id<JavaUtilCollection>)c OBJC_METHOD_FAMILY_NONE;
+ (JavaUtilEnumSet *)complementOfWithJavaUtilEnumSet:(JavaUtilEnumSet *)s;
- (void)complement;
+ (JavaUtilEnumSet *)ofWithId:(JavaLangEnum *)e;
+ (JavaUtilEnumSet *)ofWithId:(JavaLangEnum *)e1
                       withId:(JavaLangEnum *)e2;
+ (JavaUtilEnumSet *)ofWithId:(JavaLangEnum *)e1
                       withId:(JavaLangEnum *)e2
                       withId:(JavaLangEnum *)e3;
+ (JavaUtilEnumSet *)ofWithId:(JavaLangEnum *)e1
                       withId:(JavaLangEnum *)e2
                       withId:(JavaLangEnum *)e3
                       withId:(JavaLangEnum *)e4;
+ (JavaUtilEnumSet *)ofWithId:(JavaLangEnum *)e1
                       withId:(JavaLangEnum *)e2
                       withId:(JavaLangEnum *)e3
                       withId:(JavaLangEnum *)e4
                       withId:(JavaLangEnum *)e5;
+ (JavaUtilEnumSet *)ofWithId:(JavaLangEnum *)start
        withJavaLangEnumArray:(IOSObjectArray *)others;
+ (JavaUtilEnumSet *)rangeWithId:(JavaLangEnum *)start
                          withId:(JavaLangEnum *)end;
- (void)setRangeWithId:(JavaLangEnum *)start
                withId:(JavaLangEnum *)end;
- (JavaUtilEnumSet *)clone;
- (BOOL)isValidTypeWithIOSClass:(IOSClass *)cls;
- (id)copyWithZone:(NSZone *)zone;
@end
