//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/IdentityHashMap.java
//
//  Created by rwl on 2/1/13.
//

@class IOSObjectArray;
@class JavaUtilIdentityHashMap_$1;
@class JavaUtilIdentityHashMap_$2;
@class JavaUtilIdentityHashMap_IdentityHashMapEntry;
@class JavaUtilIdentityHashMap_IdentityHashMapEntrySet;
@protocol JavaUtilCollection;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilSet;

#import "JreEmulation.h"
#import "java/io/Serializable.h"
#import "java/util/AbstractCollection.h"
#import "java/util/AbstractMap.h"
#import "java/util/AbstractSet.h"
#import "java/util/Iterator.h"
#import "java/util/Map.h"
#import "java/util/MapEntry.h"

#define JavaUtilIdentityHashMap_DEFAULT_MAX_SIZE 21
#define JavaUtilIdentityHashMap_loadFactor 7500
#define JavaUtilIdentityHashMap_serialVersionUID 8188218128353913216

@interface JavaUtilIdentityHashMap : JavaUtilAbstractMap < JavaUtilMap, JavaIoSerializable, NSCopying > {
 @public
  IOSObjectArray *elementData_;
  int size__;
  int threshold_;
  int modCount_;
}

@property (nonatomic, retain) IOSObjectArray *elementData;
@property (nonatomic, assign) int size_;
@property (nonatomic, assign) int threshold;
@property (nonatomic, assign) int modCount;

+ (id)NULL_OBJECT;
- (id)init;
- (id)initWithInt:(int)maxSize;
- (int)getThresholdWithInt:(int)maxSize;
- (int)computeElementArraySize;
- (IOSObjectArray *)newElementArrayWithInt:(int)s OBJC_METHOD_FAMILY_NONE;
- (id)initWithJavaUtilMap:(id<JavaUtilMap>)map;
- (id)massageValueWithId:(id)value;
- (void)clear;
- (BOOL)containsKeyWithId:(id)key;
- (BOOL)containsValueWithId:(id)value;
- (id)getWithId:(id)key;
- (JavaUtilIdentityHashMap_IdentityHashMapEntry *)getEntryWithId:(id)key;
- (JavaUtilIdentityHashMap_IdentityHashMapEntry *)getEntryWithInt:(int)index;
+ (int)findIndexWithId:(id)key
     withNSObjectArray:(IOSObjectArray *)array;
+ (int)getModuloHashWithId:(id)key
                   withInt:(int)length;
- (id)putWithId:(id)key
         withId:(id)value;
- (void)putAllWithJavaUtilMap:(id<JavaUtilMap>)map;
- (void)rehash;
- (void)computeMaxSize;
- (id)removeWithId:(id)key;
- (id<JavaUtilSet>)entrySet;
- (id<JavaUtilSet>)keySet;
- (id<JavaUtilCollection>)values;
- (BOOL)isEqual:(id)object;
- (id)clone;
- (BOOL)isEmpty;
- (int)size;
- (void)putAllImplWithJavaUtilMap:(id<JavaUtilMap>)map;
- (id)copyWithZone:(NSZone *)zone;
@end

@interface JavaUtilIdentityHashMap_IdentityHashMapEntry : JavaUtilMapEntry {
 @public
  id iKey_;
  IOSObjectArray *elementData_;
}

@property (nonatomic, retain) id iKey;
@property (nonatomic, retain) IOSObjectArray *elementData;

- (id)initWithId:(id)theKey
          withId:(id)theValue
withNSObjectArray:(IOSObjectArray *)elementData;
- (id)clone;
- (BOOL)isEqual:(id)object;
- (NSUInteger)hash;
- (NSString *)description;
- (id)setValueWithId:(id)object;
@end

@interface JavaUtilIdentityHashMap_IdentityHashMapIterator : NSObject < JavaUtilIterator > {
 @public
  int position_;
  int lastPosition_;
  JavaUtilIdentityHashMap *associatedMap_;
  int expectedModCount_;
  id<JavaUtilMapEntry_Type> type_;
  BOOL canRemove_;
}

@property (nonatomic, assign) int position;
@property (nonatomic, assign) int lastPosition;
@property (nonatomic, retain) JavaUtilIdentityHashMap *associatedMap;
@property (nonatomic, assign) int expectedModCount;
@property (nonatomic, retain) id<JavaUtilMapEntry_Type> type;
@property (nonatomic, assign) BOOL canRemove;

- (id)initWithJavaUtilMapEntry_Type:(id<JavaUtilMapEntry_Type>)value
        withJavaUtilIdentityHashMap:(JavaUtilIdentityHashMap *)hm;
- (BOOL)hasNext;
- (void)checkConcurrentMod;
- (id)next;
- (void)remove;
@end

@interface JavaUtilIdentityHashMap_IdentityHashMapEntrySet : JavaUtilAbstractSet {
 @public
  JavaUtilIdentityHashMap *associatedMap_;
}

@property (nonatomic, retain) JavaUtilIdentityHashMap *associatedMap;

- (id)initWithJavaUtilIdentityHashMap:(JavaUtilIdentityHashMap *)hm;
- (JavaUtilIdentityHashMap *)hashMap;
- (int)size;
- (void)clear;
- (BOOL)removeWithId:(id)object;
- (BOOL)containsWithId:(id)object;
- (id<JavaUtilIterator>)iterator;
@end

@interface JavaUtilIdentityHashMap_IdentityHashMapEntrySet_$1 : NSObject < JavaUtilMapEntry_Type > {
 @public
  JavaUtilIdentityHashMap_IdentityHashMapEntrySet *this$0_;
}

@property (nonatomic, retain) JavaUtilIdentityHashMap_IdentityHashMapEntrySet *this$0;

- (id<JavaUtilMap_Entry>)getWithJavaUtilMapEntry:(JavaUtilMapEntry *)entry;
- (id)initWithJavaUtilIdentityHashMap_IdentityHashMapEntrySet:(JavaUtilIdentityHashMap_IdentityHashMapEntrySet *)outer$0;
@end

@interface JavaUtilIdentityHashMap_$1 : JavaUtilAbstractSet {
 @public
  JavaUtilIdentityHashMap *this$0_;
}

@property (nonatomic, retain) JavaUtilIdentityHashMap *this$0;

- (BOOL)containsWithId:(id)object;
- (int)size;
- (void)clear;
- (BOOL)removeWithId:(id)key;
- (id<JavaUtilIterator>)iterator;
- (id)initWithJavaUtilIdentityHashMap:(JavaUtilIdentityHashMap *)outer$0;
@end

@interface JavaUtilIdentityHashMap_$1_$1 : NSObject < JavaUtilMapEntry_Type > {
 @public
  JavaUtilIdentityHashMap_$1 *this$0_;
}

@property (nonatomic, retain) JavaUtilIdentityHashMap_$1 *this$0;

- (id)getWithJavaUtilMapEntry:(JavaUtilMapEntry *)entry;
- (id)initWithJavaUtilIdentityHashMap_$1:(JavaUtilIdentityHashMap_$1 *)outer$0;
@end

@interface JavaUtilIdentityHashMap_$2 : JavaUtilAbstractCollection {
 @public
  JavaUtilIdentityHashMap *this$0_;
}

@property (nonatomic, retain) JavaUtilIdentityHashMap *this$0;

- (BOOL)containsWithId:(id)object;
- (int)size;
- (void)clear;
- (id<JavaUtilIterator>)iterator;
- (BOOL)removeWithId:(id)object;
- (id)initWithJavaUtilIdentityHashMap:(JavaUtilIdentityHashMap *)outer$0;
@end

@interface JavaUtilIdentityHashMap_$2_$1 : NSObject < JavaUtilMapEntry_Type > {
 @public
  JavaUtilIdentityHashMap_$2 *this$0_;
}

@property (nonatomic, retain) JavaUtilIdentityHashMap_$2 *this$0;

- (id)getWithJavaUtilMapEntry:(JavaUtilMapEntry *)entry;
- (id)initWithJavaUtilIdentityHashMap_$2:(JavaUtilIdentityHashMap_$2 *)outer$0;
@end
