//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/NoSuchElementException.java
//
//  Created by rwl on 2/1/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaUtilNoSuchElementException_serialVersionUID 6769829250639411880

@interface JavaUtilNoSuchElementException : JavaLangRuntimeException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
