//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/Classes/java/util/Properties.java
//
//  Created by rwl on 2/1/13.
//

@protocol JavaUtilEnumeration;

#import "JreEmulation.h"
#import "java/util/Hashtable.h"

@interface JavaUtilProperties : JavaUtilHashtable {
}

- (NSString *)getPropertyWithNSString:(NSString *)key;
- (NSString *)getPropertyWithNSString:(NSString *)key
                         withNSString:(NSString *)defaultValue;
- (NSString *)setPropertyWithNSString:(NSString *)key
                         withNSString:(NSString *)value;
- (id<JavaUtilEnumeration>)propertyNames;
@end
