//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/rwl/src/tball/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/SortedMap.java
//
//  Created by rwl on 2/1/13.
//

@protocol JavaUtilComparator;

#import "JreEmulation.h"
#import "java/util/Map.h"

@protocol JavaUtilSortedMap < JavaUtilMap, NSObject >
- (id<JavaUtilComparator>)comparator;
- (id)firstKey;
- (id<JavaUtilSortedMap>)headMapWithId:(id)endKey;
- (id)lastKey;
- (id<JavaUtilSortedMap>)subMapWithId:(id)startKey
                               withId:(id)endKey;
- (id<JavaUtilSortedMap>)tailMapWithId:(id)startKey;
@end
